#!/usr/bin/env python3

import sys, os

opstrFile = open("decode-riscv.h", "r")
opstrOutput = open("opstr-riscv.h", "w")

opstrOutput.write('char *riscv_opstrs[] =\n{\n')

for eachLine in opstrFile:
    if 'RISCV_OP' in eachLine:
        op = eachLine[eachLine.find('RISCV_OP_')+9:eachLine.rfind(',')]
        line = '    [RISCV_OP_' + op + ']' + '\t= "' + op + '",\n'
        opstrOutput.write(line)

opstrOutput.write('};')

opstrFile.close()
opstrOutput.close()
